# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{kronos}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Relevance, Inc."]
  s.date = %q{2009-08-10}
  s.email = %q{contact@thinkrelevance.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "examples/example_helper.rb",
     "examples/lib/kronos/api_example.rb",
     "examples/lib/kronos/httparty_extensions_example.rb",
     "examples/lib/kronos/resource_configuration_example.rb",
     "examples/lib/kronos/template_example.rb",
     "examples/lib/kronos/virtual_machine_example.rb",
     "examples/lib/kronos/zone_example.rb",
     "examples/lib/kronos_example.rb",
     "kronos.gemspec",
     "lib/kronos.rb",
     "lib/kronos/api.rb",
     "lib/kronos/httparty_extensions.rb",
     "lib/kronos/resource_configuration.rb",
     "lib/kronos/sample.rb",
     "lib/kronos/template.rb",
     "lib/kronos/virtual_machine.rb",
     "lib/kronos/zone.rb",
     "script/console"
  ]
  s.homepage = %q{http://github.com/relevance/kronos}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Contegix Cloud API reference implementation}
  s.test_files = [
    "examples/example_helper.rb",
     "examples/lib/kronos/api_example.rb",
     "examples/lib/kronos/httparty_extensions_example.rb",
     "examples/lib/kronos/resource_configuration_example.rb",
     "examples/lib/kronos/template_example.rb",
     "examples/lib/kronos/virtual_machine_example.rb",
     "examples/lib/kronos/zone_example.rb",
     "examples/lib/kronos_example.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
    else
      s.add_dependency(%q<httparty>, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0"])
  end
end
